// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcdnYb5RlqEKqpLKO94IDLnmgZw_gbxrA',
    appId: '1:662151417141:web:34bc94e92282ce73a6907c',
    messagingSenderId: '662151417141',
    projectId: 'watnow-hackathon-pigon',
    authDomain: 'watnow-hackathon-pigon.firebaseapp.com',
    storageBucket: 'watnow-hackathon-pigon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbO6HWAL2sgP7nTMYZ2wA5ccHMbA-yc-k',
    appId: '1:662151417141:android:9f3feaceec08f4ffa6907c',
    messagingSenderId: '662151417141',
    projectId: 'watnow-hackathon-pigon',
    storageBucket: 'watnow-hackathon-pigon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0DSKKdyxWtVLMiwi3L5i3wNivu5IEYMc',
    appId: '1:662151417141:ios:fec686eaf3c43fc8a6907c',
    messagingSenderId: '662151417141',
    projectId: 'watnow-hackathon-pigon',
    storageBucket: 'watnow-hackathon-pigon.appspot.com',
    iosBundleId: 'com.example.pigon',
  );
}
